name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --no-cache-dir
        pip install ruff pytest
    - name: Analisis estilo (lint)
      run: |
        ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
    - name: Compilación
      run: |
        pytest
